//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVideojuegos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cliente
    {
        public Cliente()
        {
            this.Factura = new List<Factura>();
        }
    
        public int IdCliente { get; set; }
        [StringLength(10)]
        [Display(Name = "Tipo de cliente")]
        public string TipoCliente { get; set; }
        [Required]
        [StringLength(30)]
        [Display(Name = "Nombre del cliente")]
        public string Nombre { get; set; }
        [Required]
        [StringLength(30)]
        [Display(Name = "Apellido del cliente")]
        public string Apellido { get; set; }
        [StringLength(15)]
        [Display(Name = "Teléfono del cliente")]
        public string Telefono { get; set; }
        [StringLength(60)]
        [Display(Name = "Dirección del cliente")]
        public string Direccion { get; set; }
    
        public virtual List<Factura> Factura { get; set; }
    }
}
