//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVideojuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public int IdFacturaDetalle { get; set; }
        public int Secuencial { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdJuego { get; set; }
        public byte CantidadFacturada { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Juego Juego { get; set; }

        public FacturaDetalle(int secuencial, int idFactura, int idJuego, byte cantidad)
        {
            this.Secuencial = secuencial;
            this.IdFactura = idFactura;
            this.IdJuego = idJuego;
            this.CantidadFacturada = cantidad;
        }
    }
}
