//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVideojuegos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Factura
    {
        public Factura()
        {
            this.FacturaDetalle = new HashSet<FacturaDetalle>();
        }

        public Factura(DateTime fecha, decimal importe, decimal importeTotal, int idCliente, decimal iva)
        {
            this.FechaFactura = fecha;
            this.Importe = importe;
            this.ImporteTotal = importeTotal;
            this.IdCliente = idCliente;
            this.Iva = iva;
        }
    
        public int IdFactura { get; set; }
        [Required]
        [Display(Name = "Fecha Factura")]
        public System.DateTime FechaFactura { get; set; }
        [Required]
        [Display(Name ="Importe")]
        public decimal Importe { get; set; }
        [Required]
        [Display(Name = "Importe Total")]
        public decimal ImporteTotal { get; set; }
        [Required]
        [Display(Name = "IVA")]
        public decimal Iva { get; set; }
        [Required]
        [Display(Name = "Id Cliente")]
        public Nullable<int> IdCliente { get; set; }
    
        public virtual ICollection<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
