//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaVideojuegos.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Juego
    {
        public Juego()
        {
            this.FacturaDetalle = new List<FacturaDetalle>();
        }
    
        public int IdJuego { get; set; }
        [Required]
        [StringLength(30)]
        [Display(Name = "Nombre Juego")]
        public string NombreJuego { get; set; }
        [Required]
        [Display(Name = "Id Género")]
        public Nullable<byte> IdGenero { get; set; }
        [Required]
        [Display(Name = "Id Desarrollador")]
        public Nullable<short> IdDesarrollador { get; set; }
        [Required]
        [StringLength(1)]
        [Display(Name = "Clasificación")]
        public string Clasificacion { get; set; }
        [Required]
        [Display(Name = "Precio")]
        public Nullable<decimal> Precio { get; set; }
        [Display(Name = "En almacen")]
        public Nullable<short> CantidadEnStock { get; set; }
    
        public virtual Desarrollador Desarrollador { get; set; }
        public virtual List<FacturaDetalle> FacturaDetalle { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
